### ISSUE TITLE
deselecting commit changes in netbox create device script does not prevent device from being created in zabbix

### ISSUE THREAD

**Issue by Yingineer** [MajesticFalcon/Optimizing-CPE-Deployments#9]
Deselecting the Commit changes box in the Create CPE script in Netbox is intended to allow the user a dry-run of the script without posting any live data. Currently, data is still posted to Zabbix regardless of the checkbox.

**Comment by MajesticFalcon** [comment]
2ebb126fe7a212103f91af1e25fd049726afba53
